[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 14

[general]
import = [
  "./catppuccin-mocha.toml"
]

[window]
decorations = "none"
opacity = 0.9

[env]
TERM = "xterm-256color"
