[[each]]
Exit = {}

[app."Ghostty".style]
icon = ""
icon_color = "green"

[[app."Ghostty".event]]
Exec = "ghostty"

[app."Zen Browser".style]
icon = ""
icon_color = "red"

[[app."Zen Browser".event]]
Exec = "zen"

[app."Discord".style]
icon = ""
icon_color = "blue"

[[app."Discord".event]]
Exec = "discord"

[app."1Password".style]
icon = ""
icon_color = "red"

[[app."1Password".event]]
Exec = "1password"

[app."Steam".style]
icon = ""
icon_color = "blue"

[[app."Steam".event]]
Exec = "steam"

[app."Olympus".style]
icon = ""
icon_color = "magenta"

[[app."Olympus".event]]
Exec = "olympus"

[app."Godot".style]
icon = "\ue7ee"
icon_color = "blue"

[[app."Godot".event]]
Exec = "godot4"

[app."Prism Launcher".style]
icon = "󰍳"
icon_color = "green"

[[app."Prism Launcher".event]]
Exec = "prismlauncher"

[app."Nexus Mods".style]
icon = ""
icon_color = "blue"

[[app."Nexus Mods".event]]
Exec = "NexusMods.app"

[app."ALVR".style]
icon = ""
icon_color = "magenta"

[[app."ALVR".event]]
Exec = "alvr_dashboard"

[app."Keymapp".style]
icon = ""
icon_color = "green"

[[app."Keymapp".event]]
Exec = "keymapp"
