theme = "cat_invis"

[editor]
line-number = "relative"
idle-timeout = 100

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.space.f]
f = "file_picker"
t = ":sh zellij run -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- nu $ZELLIX_MOD/yazi.nu %{buffer_name}"

[keys.normal.';']
w = ":w"
x = ":wq"
r = ":reload"
f = ":format"
s = ":sh zellij run -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- nu"
m = ":sh zellij run -c -f -x 10%% -y 10%% --widht 80%% --height 80%% -- nu $ZELLIX_MOD/makefile.nu"
g = ":sh zellij run -c -d right -- gitui"
a = ":sh zellij run -c -d right -- nu $ZELLIX_MOD/ai.nu pane"
b = ":sh nu $ZELLIX_MOD/bacon.nu"
