theme = "cat_invis"

[editor]
line-number = "relative"
idle-timeout = 100
lsp.display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.space.f]
f = "file_picker"
t = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- nu $ZELLIX_MOD/yazi.nu"

[keys.normal.';']
w = ":w"
q = ":q"
x = ":wq"
r = ":reload"
s = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- nu"
m = ":sh zellij run -c -f -- nu $ZELLIX_MOD/makefile.nu"
g = ":sh zellij run -c -d right -- gitui"
a = ":sh zellij run -c -d right -- nu $ZELLIX_MOD/ai.nu pane"

[keys.normal.';'.'c']
b = ":sh nu $ZELLIX_MOD/bacon.nu"
