theme = "catppuccin_mocha"

[editor]
line-number = "relative"
idle-timeout = 100

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.space.f]
f = "file_picker"
t = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- nu $ZELLIX_MOD/yazi.nu"

# Misc Clis
[keys.normal.space.m]
g = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- gitui"
a = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- nu $ZELLIX_MOD/ai.nu"
A = ":sh zellij run -c -d right -- nu $ZELLIX_MOD/ai.nu pane"

[keys.normal.';']
s = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- nu"
r = ":sh nu $ZELLIX_MOD/makefile.nu last"
R = ":sh nu $ZELLIX_MOD/makefile.nu last wait"
m = ":sh nu $ZELLIX_MOD/makefile.nu"
M = ":sh nu $ZELLIX_MOD/makefile.nu wait"
