[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[[language]]
name = "zel"
scope = "source.zl"
injection-regex = "zel"
file-types = ["zl"]
comment-tokens = "//"
indent = { tab-width = 2, unit = "  " }
