[language-server.lsp-ai]
command = "lsp-ai"

[language-server.lsp-ai.config.memory]
file_store = { }

[language-server.lsp-ai.config.models.gemini2]
type = "gemini"
completions_endpoint = "https://generativelanguage.googleapis.com/v1beta/models/"
chat_endpoint = "https://generativelanguage.googleapis.com/v1beta/models/"
model = "gemini-2.0-flash-exp"
auth_token_env_var_name = "GOOGLE_API_KEY"

[language-server.lsp-ai.config.models.groq]
type = "open_ai"
completions_endpoint = "https://api.groq.com/openai/v1/chat/completions"
model = "llama3-70b-8192"
auth_token_env_var_name = "GROQ_KEY"

[language-server.lsp-ai.config.completion]
model = "gemini2"
parameters = {contents = [{role = "user", parts = [{text = "{CONTEXT} and {CODE}"}]}],  systemInstruction = {role = "system", parts = [{text = "You're giving the user input completion for code in his editor"}]}}

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "lsp-ai"]
