[language-server.lsp-ai]
command = "lsp-ai"

[language-server.lsp-ai.config.memory]
file_store = { }

[language-server.lsp-ai.config.models.groq]
type = "open_ai"
completions_endpoint = "https://api.groq.com/openai/v1/chat/completions"
model = "llama-3.1-8b-instant"
auth_token_env_var_name = "GROQ_KEY"

[language-server.lsp-ai.config.completion]
model = "groq"

[language-server.lsp-ai.config.completion.parameters]
max_tokens = 64
max_context = 1024

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "lsp-ai"]
