# deepseek-r1:7b
##############################
## Configuration for lsp-ai ##
##############################

[language-server.lsp-ai]
command = "lsp-ai"

[language-server.lsp-ai.config.memory]
file_store = { }

[language-server.lsp-ai.config.models.model1]
type = "ollama"
model = "qwen2.5-coder:7b"

# Action 1: Complete
[[language-server.lsp-ai.config.actions]]
action_display_name = "Complete"
model = "model1"

[[language-server.lsp-ai.config.actions.parameters.messages]]
role = "system"
content = '''
You are an AI coding assistant. Your task is to add a "Hello World" comment to the selected text.
The user's cursor position is marked by "<CURSOR>".

Follow these steps:

1. Tell me what you believe I am asking you to do.
'''

[[language-server.lsp-ai.config.actions.parameters.messages]]
role = "user"
content = '{SELECTED_TEXT}'

#################################
## Configuration for languages ##
#################################

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "lsp-ai"]
