theme = "cat_invis"

[editor]
line-number = "relative"
idle-timeout = 100
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal.space]
l = ":toggle lsp.display-inlay-hints"

[keys.normal.space.f]
f = "file_picker"
t = """:sh zellij run -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- \
      nu ~/.config/helix/scripts/yazi.nu hi %{buffer_name}"""
      
r = """:sh zellij run -c -i -- \
      nu ~/.config/helix/scripts/yazi.nu right %{buffer_name}"""
      
d = """:sh zellij run -c -i -- \
      nu ~/.config/helix/scripts/yazi.nu down %{buffer_name}"""
b = "buffer_picker"

[keys.normal.';']
w = ":w"
x = ":wbc"
X = ":wq"
q = ":bc"
Q = ":q"
r = ":reload"
f = ":format"
s = ":sh zellij run -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- nu"
m = ":sh zellij run -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- nu ~/.config/helix/scripts/makefile.nu"
a = ":sh zellij run -c -d right -- nu ~/.config/helix/scripts/ai.nu pane"
b = ":sh zellij run -c -d down -- bacon clippy"
v = ":sh zellij run -i -c -- nu ~/.config/helix/scripts/view.nu %{buffer_name}"
