[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[[language]]
name = "zel"
scope = "source.zl"
injection-regex = "zel"
file-types = ["zl"]
comment-tokens = "//"
indent = { tab-width = 2, unit = "  " }

[language-server.godot]
command = "ncat" # or nc
args = [ "127.0.0.1", "6005"]

[[language]]
name = "gdscript"
language-servers = ["godot"]

[[language]]
name = "nix"
auto-format = true
formatter = {command = "alejandra", args = ["-q"]}
